### PR TITLE
Introduce OrleansAssetOccpuancyProvider

### LINKED ISSUE #34: Introduce Orleans as AssetOccpuancyProvider
Add implementation of `AssetOccupancyProvider` using [Orleans](https://docs.microsoft.com/en-us/dotnet/orleans/overview).

### PR DESCRIPTION
**Pull request by RayMMond**
Resolve #34

### CODE REVIEW

**Comment by RayMMond** [comment]
@gdlcf88 plz review this 😃

**Comment by gdlcf88** [comment]
@RayMMond - Pure Orleans Grain usage has better performance. I think there are two better ways:
1. We don't use the repositories(with UOW, AssetOccupancy, and AssetOccupancyCount) but use Orleans's persistence.
2. We still use the repositories but cache the state in the grain for better performance.

**Comment by RayMMond** [comment]
> @RayMMond - Pure Orleans Grain usage has better performance. I think there are two better ways:
> 
> 1. We don't use the repositories(with UOW, AssetOccupancy, and AssetOccupancyCount) but use Orleans's persistence.
> 2. We still use the repositories but cache the state in the grain for better performance.

1.  I believe we should use the repositories for consistency. What if a user using default implementation of `AssetOccupancyProvider` decide to use Orleans as provider? 
1. With my limited knowledge, the "repositories with state cached" way is hard to keep data synchronized. For example, a silo is crashed and state will be loss since Orleans's `onDestroyAsync` is not a reliable way to save changed data to database.

@gdlcf88  Any ideas?

**Comment by gdlcf88** [comment]
> 1. I believe we should use the repositories for consistency. What if a user using default implementation of `AssetOccupancyProvider` decide to use Orleans as provider?

I agree that non-breaking migration is more friendly for app developers.

> 2. With my limited knowledge, the "repositories with state cached" way is hard to keep data synchronized. For example, a silo is crashed and state will be loss since Orleans's `onDestroyAsync` is not a reliable way to save changed data to database.

You are right. Consistency and high concurrency are difficult to achieve at the same time. See my new design of EShop's [InventoryGrain](https://github.com/EasyAbp/EShop/blob/8dc2e8a6427f12da29d2a382e77f6fa53f5156fc/plugins/Inventories/OrleansGrains/src/EasyAbp.EShop.Plugins.Inventories.OrleansGrains/EasyAbp/EShop/Plugins/Inventories/OrleansGrains/InventoryGrain.cs#L42) about delay persisting the inventory state, FYI.

**Comment by RayMMond** [comment]
See #44

**Pull request closed without merging**
